- name: Create nfs share and registry pv
  hosts: bastion
  gather_facts: false
  become: True
  tasks:
    - name: Initialize a disk and setup an NFS export on it
      block: 
        - name: Ensuring export registry directory dosen't exists
          file:
            state: absent
            path: "{{ registry_nfs_export }}"

        - name: Creating registry export
          file:
            state: directory
            path: "{{ registry_nfs_export }}"
            mode: 0775

        - name: Prepare disk
          parted:
            device: "{{ nfs_device }}"
            number: 1
            part_end: "100%"
            state: present  

        - name: Create xfs filesystem on /dev/vdb1
          filesystem:
            fstype: xfs
            dev: "/dev/vdb1"

        - name: Mount up device by label
          mount:
            path: "{{ registry_nfs_export }}"
            src: /dev/vdb1
            fstype: xfs
            state: mounted

        - name: Creating exports file
          template:
            src: templates/nfs_exports.j2
            dest: /etc/exports.d/openshift.exports

        - name: Activating selinux boolean (virt_use_nfs)
          seboolean:
            name: virt_use_nfs
            state: yes
            persistent: yes
       
        - name: Restarting nfs
          service:
            name: nfs-server
            state: restarted
            enabled: true
      when: nfs_registry
